name: keeper_example
description: Examples for Keeper
private: true
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  keeper:

dependency_overrides:
  keeper:
    path: ../
  keeper_codegen:
    path: ../../keeper_codegen

dev_dependencies:
  build_runner:
  keeper_codegen: