name: keeper_codegen
description: Code generator to generate mixin classes for Keeper package.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.1.1
  source_gen: ^1.1.1
  analyzer: ^2.7.0
  keeper: ^0.0.1

dependency_overrides:
  keeper:
    path: ../keeper

dev_dependencies:
  test: ^1.19.4
  build_runner: ^2.1.5
  build_test: ^2.1.4
